### ISSUE TITLE
"Repeated File Operation and WebDAV Errors in Nextcloud 'Recognize' App"

### ISSUE THREAD

**Issue by BoBBer446** [nextcloud/recognize#1089]
### Which version of recognize are you using?

6.0.1

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

28.0.1

### Which Operating system do you have installed?

Ubuntu Server 22.04

### Which database are you running Nextcloud on?

postgres:latest

### Which Docker container are you using to run Nextcloud? (if applicable)

24.0.7

### How much RAM does your server have?

16

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Multiple and repeated errors are occurring within the Nextcloud "Recognize" app during file operations and WebDAV processes. The errors include NotPermittedException during folder creation, BadRequest related to file size mismatches, and TypeError in PHP code, all pointing to possible issues with object definitions and network/storage interactions.

### Expected Behavior

The app should perform file operations and WebDAV requests without any errors. All functionalities should work as intended, including file previews and metadata handling without throwing exceptions or causing server-side issues.

### To Reproduce

Open the Nextcloud "Recognize" app.
Execute file operations such as uploading or moving files.
Observe the errors that occur during regular use, especially those related to file operations and WebDAV requests.
Consult the log files for specific error messages as detailed above.
Note: The exact reproduction steps may vary depending on how the app is used. The key point is that the errors listed are consistent and repeatable.

### Debug log

```
version: '3.8'

services:
  nextcloud:
    image: nextcloud-custom-28:latest
    container_name: nextcloud
    hostname: nextcloud-server
    volumes:
      - /home/docker-projects/nextcloud:/var/www/html
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=securepassword
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=1024M
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost
      - NEXTCLOUD_ADMIN_USER=mysuperusername-very-cool-next
      - NEXTCLOUD_ADMIN_PASSWORD=megasecure#_1
      - NEXTCLOUD_DEFAULT_PHONE_REGION=DE
    ports:
      - "8811:80"
    
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=securepassword
    hostname: nextcloud-db
    container_name: nextcloud-db
    volumes:
      - /home/docker-projects/nextcloud/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    hostname: nextcloud-redis
    container_name: nextcloud-redis
```

Dockerfile:
```
FROM nextcloud:28-apache

RUN apt-get update && \
    apt-get install -y libbz2-dev nano ffmpeg && \
    rm -rf /var/lib/apt/lists/*


RUN docker-php-ext-install bz2
```
