### ISSUE TITLE
document use of `tmpfs` with Docker

### ISSUE THREAD

**Issue by kc9jud** [nextcloud/recognize#624]
### Describe the feature you'd like to request

I realized that, since #365, Recognize is using `/tmp` pretty heavily during recognition. I also realized that the default Docker Compose configuration doesn't use a `tmpfs` for `/tmp` within the container. This means it's hammering the storage writing and reading temporary image files. If you're on spinning rust, this can be slow, and if you're on SSD/flash, this can hasten the failure of your disk.

### Describe the solution you'd like

It might be useful to document (somewhere?) that when using Docker (Compose), if the server is not memory-constrained, one should add an additional volume for `/tmp`:

`docker run`: Add `--mount type=tmpfs,destination=/tmp` to command line.

`docker compose`: Add the following to the volume section `docker-compose.yml`:
```yaml
  app:
    image: nextcloud:25
    ...
    volumes:
      - type: tmpfs
        target: /tmp
      ...
    ...
```

### Describe alternatives you've considered

Alternatively, this could/should be an issue with https://github.com/nextcloud/docker.
