### ISSUE TITLE
Can't install using nextcloud AIO in a hetzner VPS

### ISSUE THREAD

**Issue by MaxLindberg** [nextcloud/recognize#698]
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Object recognition, Face recognition, Music recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

Nextcloud Hub 3 (25.0.3)

### Which Operating system do you have installed?

Ubuntu 22.04.1

### Which Docker container are you using to run Nextcloud? (if applicable)

Nextcloud AIO v4.3.4

### How much RAM does your server have?

7.47 GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

When I'm trying to install it from Nextcloud apps I get the following error:

> Could not extract app recognize: Unable to extract symbolic link {/mnt/ncdata/tmp/oc_tmp_FcOmKC-folder/recognize/node_modules/@mapbox/node-pre-gyp/node_modules/.bin/rimraf} 

I've tried several times and with restarts and updates in between.

Also found this in the log if it helps:

> [settings] Error: Exception: Could not extract app recognize: Unable to extract symbolic link {/mnt/ncdata/tmp/oc_tmp_FcOmKC-folder/recognize/node_modules/@mapbox/node-pre-gyp/node_modules/.bin/rimraf} at <<closure>>

> 0. /var/www/html/apps/settings/lib/Controller/AppSettingsController.php line 448
   OC\Installer->downloadApp("recognize")
> 1. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 225
   OCA\Settings\Controller\AppSettingsController->enableApps(["recognize"], [])
> 2. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 133
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
> 3. /var/www/html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
> 4. /var/www/html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, ["settings.AppSettings.enableApps"])
> 5. /var/www/html/lib/base.php line 1047
   OC\Route\Router->match("/settings/apps/enable")
> 6. /var/www/html/index.php line 36
   OC::handleRequest()

> POST /settings/apps/enable
from 130.235.135.5 by max at 2023-02-21T18:00:11+00:00

### Expected Behavior

That the app is installed.

### To Reproduce

My setup is: 
A 2 vCPU, 8GB RAM Hetzner cloud vps with a 1TB hetzner storagebox mounted by: 
`//u332604.your-storagebox.de/backup /mnt/storagebox cifs seal,rw,credentials=/etc/mount-credentials.txt,uid=33,gid=0,file_mode=0770,dir_mode=0770 0 0`
Which (except for the 'seal' argument) is exactly as the AIO example configuration. uid 33 corresponds to the www-data user.

On this I run [Nextcloud AIO](https://github.com/nextcloud/all-in-one) with the following docker compose file:
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable docume
ntation. If adjusting, don't forget to also set 'DOCKER_SOCKET_PATH'!
      - type: tmpfs
        target: /tmp #for recognize app
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
    environment: # Is needed when using any of the options below
      - NEXTCLOUD_DATADIR=/mnt/storagebox/nextcloud # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
```

**Comment by matthijsbro** [comment]
It is as if you are me. I have exactly the same problem, Hetzner, VPS, 8GB, but 4vCPU. Generally everything works, but this app does not install with the same error both via CLI and web interface.

`
Error: Could not extract app recognize: Unable to extract symbolic link {/mnt/ncdata/tmp/oc_tmp_aFdFFp-folder/recognize/node_modules/@mapbox/node-pre-gyp/node_modules/.bin/rimraf}
`

**Comment by matthijsbro** [comment]
Can't say that about the logs. Mine are full with different notion of this
below. But that seems unrelated. I don't know about the storage, i've had a
Yunohost install of Nextcloud before where I also mounted this storage, but
with webdav. That never gave me a problem. But I'm not very knowledgeble
about this.

`
[files_antivirus] Error: RuntimeException: The ClamAV module is not in
daemon mode. at <<closure>>

0. /var/www/html/custom_apps/files_antivirus/lib/Scanner/ScannerBase.php
line 86
   OCA\Files_Antivirus\Scanner\ExternalClam->initScanner()
1.
/var/www/html/custom_apps/files_antivirus/lib/BackgroundJob/BackgroundScanner.php
line 313
   OCA\Files_Antivirus\Scanner\ScannerBase->scan(OCA\Files_Antivirus\Item
{})

`

Op di 21 feb. 2023 om 22:08 schreef MaxLindberg ***@***.***>:

**Comment by matthijsbro** [comment]
Can't say that about the logs. Mine are full with different notion of this
below. But that seems unrelated. I don't know about the storage, i've had a
Yunohost install of Nextcloud before where I also mounted this storage, but
with webdav. That never gave me a problem. But I'm not very knowledgeble
about this.

I don't have the Maps app installed at all. 

```
[files_antivirus] Error: RuntimeException: The ClamAV module is not in
daemon mode. at <<closure>>

0. /var/www/html/custom_apps/files_antivirus/lib/Scanner/ScannerBase.php
line 86
   OCA\Files_Antivirus\Scanner\ExternalClam->initScanner()
1.
/var/www/html/custom_apps/files_antivirus/lib/BackgroundJob/BackgroundScanner.php
line 313
   OCA\Files_Antivirus\Scanner\ScannerBase->scan(OCA\Files_Antivirus\Item
{})
```

**Comment by matthijsbro** [comment]
I disabled ClamAV to get a clear look at what's in my logs. After the error of being 'Unable to extact symbolic link' it now gives me several of these:

`
[PHP] Error: Error: rmdir(/mnt/ncdata/tmp/oc_tmp_bHPCPB-folder): Directory not empty at /var/www/html/lib/private/legacy/OC_Helper.php#183 at <<closure>>

0. <<closure>>
   OC\Log\ErrorHandler::onError(2, "rmdir(/mnt/ncda ... y", "/var/www/html/l ... p", 183)
1. /var/www/html/lib/private/legacy/OC_Helper.php line 183
   rmdir("/mnt/ncdata/tmp/oc_tmp_bHPCPB-folder")
2. /var/www/html/lib/private/TempManager.php line 162
   OC_Helper::rmdirr("/mnt/ncdata/tmp/oc_tmp_bHPCPB-folder")
3. /var/www/html/lib/private/TempManager.php line 152
   OC\TempManager->cleanFiles(["/mnt/ncdata/tm ... "])
4. <<closure>>
   OC\TempManager->clean()

POST /settings/apps/enable
from 80.60.190.47 by matthijs at 2023-02-21T21:56:43+00:00
`

**Comment by matthijsbro** [comment]
Allright final thought for tonight. This error of non-empty dir is just that it is not cleaning up after itself. There is indeed a dir in you nextcloud data dir called data/tmp/oc_tmp_bHPCPB-folder/recognize/ and it is not deleted. 

My new guess is that recognize is a large app, it's just about 78MB as a .tar and extracted about 264MB. Perhaps PHP has not enough time to download it completely, or not enough memory or time to extract it completely.

**Comment by marcelklehr** [comment]
Generally when installing via UI doesn't work, installing via occ does the trick

**Comment by matthijsbro** [comment]
> Generally when installing via UI doesn't work, installing via occ does the trick

No, I tried either way and it gives the same error.

**Comment by mickare** [comment]
Hi @MaxLindberg, did you try to use a Docker volume with CIFS and use it directly?

**Warning I just copied stuff together, without any guarantees. I'm just curious if this works. :)**

Links:
- https://www.jeffgeerling.com/blog/2021/making-sure-symlinks-work-on-cifssmb-mounted-shares
- https://nerdblog.steinkopf.net/2017/12/persistente-docker-volumes-mit-nfs-und-cifs/
- https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir


```yaml
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed
  nextcloud_aio_datadir:
    name: nextcloud_aio_datadir
    driver_opts:
      type: "cifs"
      device: "//u332604.your-storagebox.de/backup"
      o: "seal,rw,mfsymlinks,credentials=/etc/mount-credentials.txt,uid=33,gid=0,file_mode=0770,dir_mode=0770"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'DOCKER_SOCKET_PATH'!
      - type: tmpfs
        target: /tmp #for recognize app
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
    environment: # Is needed when using any of the options below
      - NEXTCLOUD_DATADIR=nextcloud_aio_datadir

```

I think you are missing the `mfsymlinks` option for the storage box mount, else symbolic links are not supported.

Also `forcedirectio` may be another performance parameter that may help.
